export const activities = [
	{
		numberOfDays: 8,
		iconSrc: 'video-platform',
		srcset2: 'video-platform@2x',
		srcset3: 'video-platform@3x',
		subjectCompany: 'cloud orchestration',
		subjectCompanyUrl: '#',
		verb: 'replaced',
		objectCompany: 'microsoft',
		objectCompanyStyle: 'strike-through',
		numberOfProperties: 1
	},
	{
		numberOfDays: 10,
		iconSrc: 'content-delivery',
		srcset2: 'content-delivery@2x',
		srcset3: 'content-delivery@3x',
		subjectCompany: 'express scripts',
		subjectCompanyUrl: '#',
		verb: 'replaced',
		objectCompany: 'microsoft',
		objectCompanyStyle: 'strike-through',
		numberOfProperties: 1
	},
	{
		numberOfDays: 12,
		iconSrc: 'waf-d-dos-security',
		srcset2: 'waf-d-dos-security@2x',
		srcset3: 'waf-d-dos-security@3x',
		subjectCompany: 'kaiser permanente',
		subjectCompanyUrl: '#',
		verb: 'replaced',
		objectCompany: 'microsoft',
		objectCompanyStyle: 'strike-through',
		numberOfProperties: 1
	},
	{
		numberOfDays: 14,
		iconSrc: 'traffic-management',
		srcset2: 'traffic-management@2x',
		srcset3: 'traffic-management@3x',
		subjectCompany: 'molina healthcare',
		subjectCompanyUrl: '#',
		verb: 'replaced',
		objectCompany: 'microsoft',
		objectCompanyStyle: 'strike-through',
		numberOfProperties: 1
	},
	{
		numberOfDays: 15,
		iconSrc: 'dns',
		srcset2: 'dns@2x',
		srcset3: 'dns@3x',
		subjectCompany: 'express scripts',
		subjectCompanyUrl: '#',
		verb: 'replaced',
		objectCompany: 'microsoft',
		objectCompanyStyle: 'strike-through',
		numberOfProperties: 1
	},
	{
		numberOfDays: 16,
		iconSrc: 'performance-monitoring',
		srcset2: 'performance-monitoring@2x',
		srcset3: 'performance-monitoring@3x',
		subjectCompany: 'kaiser permanente',
		subjectCompanyUrl: '#',
		verb: 'replaced',
		objectCompany: 'microsoft',
		objectCompanyStyle: 'strike-through',
		numberOfProperties: 1
	},
	{
		numberOfDays: 17,
		iconSrc: 'saas',
		srcset2: 'saas@2x',
		srcset3: 'saas@3x',
		subjectCompany: 'molina healthcare',
		subjectCompanyUrl: '#',
		verb: 'replaced',
		objectCompany: 'microsoft',
		objectCompanyStyle: 'strike-through',
		numberOfProperties: 1
	},
	{
		numberOfDays: 18,
		iconSrc: 'content-delivery',
		srcset2: 'content-delivery@2x',
		srcset3: 'content-delivery@3x',
		subjectCompany: 'microsoft',
		subjectCompanyUrl: '',
		verb: 'launched',
		objectCompany: 'm-cloud',
	}
];
